package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import com.cooperativajsf.entity.Coop$Cuenta;
import com.cooperativajsf.entity.Coop$Tipomovimiento;
import java.math.BigDecimal;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coop.Movimiento generated by hbm2java
 */
@Entity
@Table(name = "COOP$_MOVIMIENTO",
         schema = "SYSTEM"
)
public class Coop$Movimiento implements java.io.Serializable {

    @Id
    @Column(name = "IDMOVIMIENTO", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "AutoIdMovimiento")
    private BigDecimal idmovimiento;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NUMEROCUENTA")
    private Coop$Cuenta coop$Cuenta;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IDTIPOMOVIMIENTO")
    private Coop$Tipomovimiento coop$Tipomovimiento;

    @Column(name = "VALOR", precision = 22, scale = 0)
    private BigDecimal valor;

    public Coop$Movimiento() {
    }

    public Coop$Movimiento(BigDecimal idmovimiento) {
        this.idmovimiento = idmovimiento;
    }

    public Coop$Movimiento(BigDecimal idmovimiento, Coop$Cuenta coop$Cuenta, Coop$Tipomovimiento coop$Tipomovimiento, BigDecimal valor) {
        this.idmovimiento = idmovimiento;
        this.coop$Cuenta = coop$Cuenta;
        this.coop$Tipomovimiento = coop$Tipomovimiento;
        this.valor = valor;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 79 * hash + Objects.hashCode(this.idmovimiento);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Movimiento other = (Coop$Movimiento) obj;
        if (!Objects.equals(this.idmovimiento, other.idmovimiento)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Movimiento{" + "idmovimiento=" + idmovimiento + ", coop$Cuenta=" + coop$Cuenta + ", coop$Tipomovimiento=" + coop$Tipomovimiento + ", valor=" + valor + '}';
    }

    public BigDecimal getIdmovimiento() {
        return this.idmovimiento;
    }

    public void setIdmovimiento(BigDecimal idmovimiento) {
        this.idmovimiento = idmovimiento;
    }

    public Coop$Cuenta getCoop$Cuenta() {
        return this.coop$Cuenta;
    }

    public void setCoop$Cuenta(Coop$Cuenta coop$Cuenta) {
        this.coop$Cuenta = coop$Cuenta;
    }

    public Coop$Tipomovimiento getCoop$Tipomovimiento() {
        return this.coop$Tipomovimiento;
    }

    public void setCoop$Tipomovimiento(Coop$Tipomovimiento coop$Tipomovimiento) {
        this.coop$Tipomovimiento = coop$Tipomovimiento;
    }

    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

}
