package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import com.cooperativajsf.entity.Coop$Razonsocial;
import java.math.BigDecimal;
import java.util.Objects;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Coop.Personajuridica generated by hbm2java
 */
@Entity
@Table(name = "COOP$_PERSONAJURIDICA",
         schema = "SYSTEM"
)
public class Coop$Personajuridica implements java.io.Serializable {

    @Id
    @Column(name = "NIT", unique = true, nullable = false, length = 10)
    private String nit;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IDRAZONSOCIAL")
    private Coop$Razonsocial coop$Razonsocial;

    @Column(name = "ANOFUNDACION", precision = 22, scale = 0)
    private BigDecimal anofundacion;

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
    private Coop$Persona persona;

    public Coop$Personajuridica() {

    }

    public Coop$Personajuridica(String nit) {
        this.nit = nit;
    }

    public Coop$Personajuridica(String nit, Coop$Razonsocial coop$Razonsocial, BigDecimal anofundacion, Coop$Persona persona) {
        this.nit = nit;
        this.coop$Razonsocial = coop$Razonsocial;
        this.anofundacion = anofundacion;
        this.persona = persona;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + Objects.hashCode(this.nit);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Personajuridica other = (Coop$Personajuridica) obj;
        if (!Objects.equals(this.nit, other.nit)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Personajuridica{" + "nit=" + nit + ", coop$Razonsocial=" + coop$Razonsocial + ", anofundacion=" + anofundacion + ", persona=" + persona + '}';
    }

    /**
     * @return the nit
     */
    public String getNit() {
        return nit;
    }

    /**
     * @param nit the nit to set
     */
    public void setNit(String nit) {
        this.nit = nit;
    }

    /**
     * @return the coop$Razonsocial
     */
    public Coop$Razonsocial getCoop$Razonsocial() {
        return coop$Razonsocial;
    }

    /**
     * @param coop$Razonsocial the coop$Razonsocial to set
     */
    public void setCoop$Razonsocial(Coop$Razonsocial coop$Razonsocial) {
        this.coop$Razonsocial = coop$Razonsocial;
    }

    /**
     * @return the anofundacion
     */
    public BigDecimal getAnofundacion() {
        return anofundacion;
    }

    /**
     * @param anofundacion the anofundacion to set
     */
    public void setAnofundacion(BigDecimal anofundacion) {
        this.anofundacion = anofundacion;
    }

    /**
     * @return the persona
     */
    public Coop$Persona getPersona() {
        return persona;
    }

    /**
     * @param persona the persona to set
     */
    public void setPersona(Coop$Persona persona) {
        this.persona = persona;
    }

}
