package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coop.Razonsocial generated by hbm2java
 */
@Entity
@Table(name = "COOP$_RAZONSOCIAL",
         schema = "SYSTEM"
)
public class Coop$Razonsocial implements java.io.Serializable {

    @Id
    @Column(name = "IDRAZONSOCIAL", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "AutoIdRazonSocial")
    private BigDecimal idrazonsocial;

    @Column(name = "DESCRIPCION", length = 100)
    private String descripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coop$Razonsocial")
    private Set coop$Personajuridicas = new HashSet(0);

    public Coop$Razonsocial() {
    }

    public Coop$Razonsocial(BigDecimal idrazonsocial) {
        this.idrazonsocial = idrazonsocial;
    }

    public Coop$Razonsocial(BigDecimal idrazonsocial, String descripcion, Set coop$Personajuridicas) {
        this.idrazonsocial = idrazonsocial;
        this.descripcion = descripcion;
        this.coop$Personajuridicas = coop$Personajuridicas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.idrazonsocial);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Razonsocial other = (Coop$Razonsocial) obj;
        if (!Objects.equals(this.idrazonsocial, other.idrazonsocial)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Razonsocial{" + "idrazonsocial=" + idrazonsocial + ", descripcion=" + descripcion + ", coop$Personajuridicas=" + coop$Personajuridicas + '}';
    }

    public BigDecimal getIdrazonsocial() {
        return this.idrazonsocial;
    }

    public void setIdrazonsocial(BigDecimal idrazonsocial) {
        this.idrazonsocial = idrazonsocial;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getCoop$Personajuridicas() {
        return this.coop$Personajuridicas;
    }

    public void setCoop$Personajuridicas(Set coop$Personajuridicas) {
        this.coop$Personajuridicas = coop$Personajuridicas;
    }

}
