package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Coop.Persona generated by hbm2java
 */
@Entity
@Table(name = "COOP$_PERSONA",
         schema = "SYSTEM"
)
public class Coop$Persona implements java.io.Serializable {

    @Id
    @Column(name = "DOCUMENTO", unique = true, nullable = false, length = 10)
    private String documento;

    @Column(name = "RUT", length = 9)
    private String rut;

    @Column(name = "TIPOPERSONA", length = 1)
    private String tipopersona;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coop$Persona")
    private Set coop$Cuentas = new HashSet(0);

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
    private Coop$Logueopersona logueopersona;

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
    private Coop$Personajuridica personajuridica;

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
    private Coop$Personanatural personanatural;

    public Coop$Persona() {
        personanatural = new Coop$Personanatural();
        personajuridica = new Coop$Personajuridica();
        logueopersona = new Coop$Logueopersona();
    }

    public Coop$Persona(String documento) {
        this.documento = documento;
    }

    public Coop$Persona(String documento, String rut, String tipopersona, Coop$Logueopersona logueopersona, Coop$Personajuridica personajuridica, Coop$Personanatural personanatural) {
        this.documento = documento;
        this.rut = rut;
        this.tipopersona = tipopersona;
        this.logueopersona = logueopersona;
        this.personajuridica = personajuridica;
        this.personanatural = personanatural;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.documento);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Persona other = (Coop$Persona) obj;
        if (!Objects.equals(this.documento, other.documento)) {
            return false;
        }
        return true;
    }

    /**
     * @return the documento
     */
    public String getDocumento() {
        return documento;
    }

    /**
     * @param documento the documento to set
     */
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    /**
     * @return the rut
     */
    public String getRut() {
        return rut;
    }

    /**
     * @param rut the rut to set
     */
    public void setRut(String rut) {
        this.rut = rut;
    }

    /**
     * @return the tipopersona
     */
    public String getTipopersona() {
        return tipopersona;
    }

    /**
     * @param tipopersona the tipopersona to set
     */
    public void setTipopersona(String tipopersona) {
        this.tipopersona = tipopersona;
    }

    /**
     * @return the coop$Cuentas
     */
    public Set getCoop$Cuentas() {
        return coop$Cuentas;
    }

    /**
     * @param coop$Cuentas the coop$Cuentas to set
     */
    public void setCoop$Cuentas(Set coop$Cuentas) {
        this.coop$Cuentas = coop$Cuentas;
    }

    /**
     * @return the logueopersona
     */
    public Coop$Logueopersona getLogueopersona() {
        return logueopersona;
    }

    /**
     * @param logueopersona the logueopersona to set
     */
    public void setLogueopersona(Coop$Logueopersona logueopersona) {
        this.logueopersona = logueopersona;
    }

    /**
     * @return the personajuridica
     */
    public Coop$Personajuridica getPersonajuridica() {
        return personajuridica;
    }

    /**
     * @param personajuridica the personajuridica to set
     */
    public void setPersonajuridica(Coop$Personajuridica personajuridica) {
        this.personajuridica = personajuridica;
    }

    /**
     * @return the personanatural
     */
    public Coop$Personanatural getPersonanatural() {
        return personanatural;
    }

    /**
     * @param personanatural the personanatural to set
     */
    public void setPersonanatural(Coop$Personanatural personanatural) {
        this.personanatural = personanatural;
    }

    @Override
    public String toString() {
        return "Coop$Persona{" + "documento=" + documento + ", rut=" + rut + ", tipopersona=" + tipopersona + ", coop$Cuentas=" + coop$Cuentas + ", logueopersona=" + logueopersona + ", personajuridica=" + personajuridica + ", personanatural=" + personanatural + '}';
    }

}
