package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import com.cooperativajsf.entity.Coop$Tipodocumento;
import java.util.Objects;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Coop.Personanatural generated by hbm2java
 */
@Entity
@Table(name = "COOP$_PERSONANATURAL",
         schema = "SYSTEM"
)
public class Coop$Personanatural implements java.io.Serializable {

    @Id
    @Column(name = "DOCUMENTO", unique = true, nullable = false, length = 10)
    private String documento;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIPODOCUMENTO")
    private Coop$Tipodocumento coop$Tipodocumento;

    @Column(name = "NOMBRE", length = 80)
    private String nombre;

    @Column(name = "APELLIDO", length = 250)
    private String apellido;

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
    private Coop$Persona persona;

    public Coop$Personanatural() {

    }

    public Coop$Personanatural(String documento) {
        this.documento = documento;
    }

    public Coop$Personanatural(String documento, Coop$Tipodocumento coop$Tipodocumento, String nombre, String apellido, Coop$Persona persona) {
        this.documento = documento;
        this.coop$Tipodocumento = coop$Tipodocumento;
        this.nombre = nombre;
        this.apellido = apellido;
        this.persona = persona;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.documento);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Personanatural other = (Coop$Personanatural) obj;
        if (!Objects.equals(this.documento, other.documento)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Personanatural{" + "documento=" + documento + ", coop$Tipodocumento=" + coop$Tipodocumento + ", nombre=" + nombre + ", apellido=" + apellido + ", persona=" + persona + '}';
    }

    /**
     * @return the documento
     */
    public String getDocumento() {
        return documento;
    }

    /**
     * @param documento the documento to set
     */
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    /**
     * @return the coop$Tipodocumento
     */
    public Coop$Tipodocumento getCoop$Tipodocumento() {
        return coop$Tipodocumento;
    }

    /**
     * @param coop$Tipodocumento the coop$Tipodocumento to set
     */
    public void setCoop$Tipodocumento(Coop$Tipodocumento coop$Tipodocumento) {
        this.coop$Tipodocumento = coop$Tipodocumento;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the apellido
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * @param apellido the apellido to set
     */
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    /**
     * @return the persona
     */
    public Coop$Persona getPersona() {
        return persona;
    }

    /**
     * @param persona the persona to set
     */
    public void setPersona(Coop$Persona persona) {
        this.persona = persona;
    }

}
