package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import com.cooperativajsf.entity.Coop$Moneda;
import com.cooperativajsf.entity.Coop$Persona;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Check;

/**
 * Coop.Cuenta generated by hbm2java
 */
@Entity
@Table(name = "COOP$_CUENTA",
         schema = "SYSTEM"
)
public class Coop$Cuenta implements java.io.Serializable {

    @Id
    @Column(name = "NUMEROCUENTA", unique = true, nullable = false, length = 12)
    private String numerocuenta;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCUMENTO")
    private Coop$Persona coop$Persona;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IDMONEDA")
    private Coop$Moneda coop$Moneda;

    @Column(name = "SALDO", precision = 22, scale = 0)
    private BigDecimal saldo;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coop$Cuenta")
    private Set coop$Movimientos = new HashSet(0);

    public Coop$Cuenta() {
    }

    public Coop$Cuenta(String numerocuenta) {
        this.numerocuenta = numerocuenta;
    }

    public Coop$Cuenta(String numerocuenta, Coop$Persona coop$Persona, Coop$Moneda coop$Moneda, BigDecimal saldo, Set coop$Movimientos) {
        this.numerocuenta = numerocuenta;
        this.coop$Persona = coop$Persona;
        this.coop$Moneda = coop$Moneda;
        this.saldo = saldo;
        this.coop$Movimientos = coop$Movimientos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 61 * hash + Objects.hashCode(this.numerocuenta);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Cuenta other = (Coop$Cuenta) obj;
        if (!Objects.equals(this.numerocuenta, other.numerocuenta)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Cuenta{" + "numerocuenta=" + numerocuenta + ", coop$Persona=" + coop$Persona + ", coop$Moneda=" + coop$Moneda + ", saldo=" + saldo + ", coop$Movimientos=" + coop$Movimientos + '}';
    }

    public String getNumerocuenta() {
        return this.numerocuenta;
    }

    public void setNumerocuenta(String numerocuenta) {
        this.numerocuenta = numerocuenta;
    }

    public Coop$Persona getCoop$Persona() {
        return this.coop$Persona;
    }

    public void setCoop$Persona(Coop$Persona coop$Persona) {
        this.coop$Persona = coop$Persona;
    }

    public Coop$Moneda getCoop$Moneda() {
        return this.coop$Moneda;
    }

    public void setCoop$Moneda(Coop$Moneda coop$Moneda) {
        this.coop$Moneda = coop$Moneda;
    }

    public BigDecimal getSaldo() {
        return this.saldo;
    }

    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }

    public Set getCoop$Movimientos() {
        return this.coop$Movimientos;
    }

    public void setCoop$Movimientos(Set coop$Movimientos) {
        this.coop$Movimientos = coop$Movimientos;
    }

}
