package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coop.Tipodocumento generated by hbm2java
 */
@Entity
@Table(name = "COOP$_TIPODOCUMENTO",
         schema = "SYSTEM"
)
public class Coop$Tipodocumento implements java.io.Serializable {

    @Id
    @Column(name = "IDTIPODOCUMENTO", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "AutoIdTDocumento")
    private BigDecimal idtipodocumento;

    @Column(name = "DESCRIPCION", length = 50)
    private String descripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coop$Tipodocumento")
    private Set coop$Personanaturals = new HashSet(0);

    public Coop$Tipodocumento() {
    }

    public Coop$Tipodocumento(BigDecimal idtipodocumento) {
        this.idtipodocumento = idtipodocumento;
    }

    public Coop$Tipodocumento(BigDecimal idtipodocumento, String descripcion, Set coop$Personanaturals) {
        this.idtipodocumento = idtipodocumento;
        this.descripcion = descripcion;
        this.coop$Personanaturals = coop$Personanaturals;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.idtipodocumento);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Tipodocumento other = (Coop$Tipodocumento) obj;
        if (!Objects.equals(this.idtipodocumento, other.idtipodocumento)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Tipodocumento{" + "idtipodocumento=" + idtipodocumento + ", descripcion=" + descripcion + ", coop$Personanaturals=" + coop$Personanaturals + '}';
    }

    public BigDecimal getIdtipodocumento() {
        return this.idtipodocumento;
    }

    public void setIdtipodocumento(BigDecimal idtipodocumento) {
        this.idtipodocumento = idtipodocumento;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getCoop$Personanaturals() {
        return this.coop$Personanaturals;
    }

    public void setCoop$Personanaturals(Set coop$Personanaturals) {
        this.coop$Personanaturals = coop$Personanaturals;
    }

}
