package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Coop.Logueopersona generated by hbm2java
 */
@Entity
@Table(name = "COOP$_LOGUEOPERSONA",
         schema = "SYSTEM"
)
public class Coop$Logueopersona implements java.io.Serializable {

    @Id
    @Column(name = "DOCUMENTO", unique = true, nullable = false, length = 10)
    private String documento;

    @Column(name = "CONTRASENA", length = 250)
    private String contrasena;

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
    private Coop$Persona persona;

    public Coop$Logueopersona() {

    }

    public Coop$Logueopersona(String documento) {
        this.documento = documento;
    }

    public Coop$Logueopersona(String documento, String contrasena, Coop$Persona persona) {
        this.documento = documento;
        this.contrasena = contrasena;
        this.persona = persona;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Logueopersona other = (Coop$Logueopersona) obj;
        if (!Objects.equals(this.documento, other.documento)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Logueopersona{" + "documento=" + documento + ", contrasena=" + contrasena + ", persona=" + persona + '}';
    }

    /**
     * @return the documento
     */
    public String getDocumento() {
        return documento;
    }

    /**
     * @param documento the documento to set
     */
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    /**
     * @return the contrasena
     */
    public String getContrasena() {
        return contrasena;
    }

    /**
     * @param contrasena the contrasena to set
     */
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    /**
     * @return the persona
     */
    public Coop$Persona getPersona() {
        return persona;
    }

    /**
     * @param persona the persona to set
     */
    public void setPersona(Coop$Persona persona) {
        this.persona = persona;
    }

}
