package com.cooperativajsf.entity;
// Generated 2/05/2021 08:07:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coop.Tipomovimiento generated by hbm2java
 */
@Entity
@Table(name = "COOP$_TIPOMOVIMIENTO",
         schema = "SYSTEM"
)
public class Coop$Tipomovimiento implements java.io.Serializable {

    @Id
    @Column(name = "IDTIPOMOVIMIENTO", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "AutoIdTipoMovimiento")
    private BigDecimal idtipomovimiento;

    @Column(name = "DESCRIPCION", length = 15)
    private String descripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coop$Tipomovimiento")
    private Set coop$Movimientos = new HashSet(0);

    public Coop$Tipomovimiento() {
    }

    public Coop$Tipomovimiento(BigDecimal idtipomovimiento) {
        this.idtipomovimiento = idtipomovimiento;
    }

    public Coop$Tipomovimiento(BigDecimal idtipomovimiento, String descripcion, Set coop$Movimientos) {
        this.idtipomovimiento = idtipomovimiento;
        this.descripcion = descripcion;
        this.coop$Movimientos = coop$Movimientos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + Objects.hashCode(this.idtipomovimiento);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coop$Tipomovimiento other = (Coop$Tipomovimiento) obj;
        if (!Objects.equals(this.idtipomovimiento, other.idtipomovimiento)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Coop$Tipomovimiento{" + "idtipomovimiento=" + idtipomovimiento + ", descripcion=" + descripcion + ", coop$Movimientos=" + coop$Movimientos + '}';
    }

    public BigDecimal getIdtipomovimiento() {
        return this.idtipomovimiento;
    }

    public void setIdtipomovimiento(BigDecimal idtipomovimiento) {
        this.idtipomovimiento = idtipomovimiento;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getCoop$Movimientos() {
        return this.coop$Movimientos;
    }

    public void setCoop$Movimientos(Set coop$Movimientos) {
        this.coop$Movimientos = coop$Movimientos;
    }

}
